name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  formatting-check:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - name: Test Formatting
      run: sbt scalafmtCheckAll
  test-jvm:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - name: Test
      run: sbt rootJVM/test
  test-native:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 21
    - name: Install scala-native dependencies
      run: sudo apt-get install clang libstdc++-12-dev libgc-dev
    - name: Test
      run: sbt rootNative/test
    - name: Stress Test with Lower Memory
      run: env GC_MAXIMUM_HEAP_SIZE=128M sbt 'rootNative/testOnly StressTest'
